# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nLUiG737BJIYj60CpOzUAB3rO9RCP_8o
"""

R1 = float(input("Enter R1 value: "))
R2 = float(input("Enter R2 value: "))

total = R1 + R2

p1 = R1 / total
p2 = R2 / total
print("\n total=",total)
print("p1 =", p1)
print("P1 Percentage =",p1*100,"%")
print("p2 =", p2)
print("P2 Percentage =",p2*100,"%")
print("p1 + p2 =", p1 + p2)